{% set name = "dmff" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmodeling/DMFF/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b38847ec0be34360c885f4c98dea93df1dc9ccd0e48dca84af5bac23f105ff26

build:
  number: 1
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy >=1.18
    # https://github.com/google/jax/issues/17660
    # latest jax2tf requires TF 2.15, but it's not ready on conda-forge
    # However, pin jax to <0.4.15 leads to the following error:
    # chex 0.1.83 has requirement jax>=0.4.16, but you have jax 0.4.14.
    # flax 0.7.5 has requirement jax>=0.4.19, but you have jax 0.4.14.
    # The conda-forge packages are broken
    - jax >=0.4.1
    - jax-md >=0.2.4
    - mdtraj
    - optax >=0.1.4
    - pymbar >=4.0.0
    - openmm >=7.6.0
    - rdkit
    - freud
    - networkx >=3.0
    - tqdm
    - jaxopt >=0.8.0

test:
  imports:
    - dmff
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deepmodeling/DMFF
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: DMFF (Differentiable Molecular Force Field) is a Jax-based python package that provides a full differentiable implementation of molecular force field models.
  doc_url: https://github.com/deepmodeling/DMFF
  dev_url: https://github.com/deepmodeling/DMFF

extra:
  recipe-maintainers:
    - njzjz
    - WangXinyan940
